# -*- coding: utf-8 -*-
"""application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2jDMwEVrmaPWvoOXxWK1SmoS18csVbl
"""

import numpy as np
import pandas as pd
import scipy.stats as stats
from scipy.optimize import minimize_scalar
from scipy.special import lambertw
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
import warnings

warnings.filterwarnings('ignore')

# Set publication-quality figure aesthetics
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.size'] = 8
plt.rcParams['axes.labelsize'] = 9
plt.rcParams['axes.titlesize'] = 9

# -------------------------------------------------------------------------
# 1. FETCH REAL EMPIRICAL MARKET DATA
# -------------------------------------------------------------------------
START_DATE = "2020-01-01"
END_DATE = "2023-12-31"
TICKER = "^GSPC"  # S&P 500 Index

print(f"Downloading daily market data for {TICKER} from {START_DATE} to {END_DATE}...")
sp500 = yf.download(TICKER, start=START_DATE, end=END_DATE)

# Calculate daily net log-returns: R_t = ln(P_t / P_{t-1})
sp500['Returns'] = np.log(sp500['Close'] / sp500['Close'].shift(1))
real_data = sp500['Returns'].dropna().values

print(f"Successfully loaded {len(real_data)} empirical daily returns.\n")

# -------------------------------------------------------------------------
# 2. PROPOSED OBULEZI TRANSFORMATION & PROFILE LIKELIHOOD
# -------------------------------------------------------------------------

def obulezi_transform(x, lmbda):
    x = np.asarray(x, dtype=np.float64)
    sgn = np.sign(x)
    abs_x = np.abs(x)
    if np.isclose(lmbda, 0.0):
        return x
    elif lmbda > 0:
        return sgn * (1.0 / lmbda) * np.log(1.0 + lmbda * abs_x * np.exp(lmbda * abs_x))
    else:
        abs_lmbda = np.abs(lmbda)
        w_val = np.real(lambertw(abs_lmbda * abs_x))
        return sgn * (1.0 / abs_lmbda) * w_val

def obulezi_jacobian_log(x, lmbda):
    x = np.asarray(x, dtype=np.float64)
    abs_x = np.abs(x)
    if np.isclose(lmbda, 0.0):
        return np.zeros_like(x)
    elif lmbda > 0:
        num = 1.0 + lmbda * abs_x
        den = 1.0 + lmbda * abs_x * np.exp(lmbda * abs_x)
        return np.log(num) - np.log(den) + (lmbda * abs_x)
    else:
        abs_lmbda = np.abs(lmbda)
        w_val = np.real(lambertw(abs_lmbda * abs_x))
        mask = abs_x > 1e-12
        log_j = np.zeros_like(x)
        log_j[mask] = np.log(w_val[mask]) - np.log(abs_lmbda * abs_x[mask] * (1.0 + w_val[mask]))
        return log_j

def profile_log_lik_obulezi(lmbda, x):
    n = len(x)
    y = obulezi_transform(x, lmbda)
    y_var = np.var(y, ddof=0)
    if y_var <= 1e-12 or np.isnan(y_var) or np.isinf(y_var):
        return 1e10
    log_j = obulezi_jacobian_log(x, lmbda)
    return -(-0.5 * n * np.log(2 * np.pi) - 0.5 * n * np.log(y_var) - 0.5 * n + np.sum(log_j))

def fit_obulezi(x):
    res = minimize_scalar(profile_log_lik_obulezi, bounds=(-30.0, 30.0), args=(x,), method='bounded')
    return obulezi_transform(x, res.x)

# -------------------------------------------------------------------------
# 3. TABLE 1 TRANSFORMATION FUNCTIONS
# -------------------------------------------------------------------------

def transform_box_cox(x):
    x_pos = x - np.min(x) + 0.001
    y, _ = stats.boxcox(x_pos)
    return y

def transform_bickel_doksum(x, lmbda=0.5):
    sgn = np.sign(x)
    abs_x = np.abs(x)
    return (np.power(abs_x, lmbda) * sgn - 1.0) / lmbda

def transform_manly(x, lmbda=0.1):
    return (np.exp(lmbda * x) - 1.0) / lmbda if not np.isclose(lmbda, 0) else x

def transform_modulus(x, lmbda=0.5):
    sgn = np.sign(x)
    abs_x = np.abs(x)
    return sgn * ((np.power(abs_x + 1.0, lmbda) - 1.0) / lmbda)

def transform_yeo_johnson(x):
    y, _ = stats.yeojohnson(x)
    return y

def transform_dual_power(x, lmbda=0.5):
    x_pos = x - np.min(x) + 0.001
    return (np.power(x_pos, lmbda) - np.power(x_pos, -lmbda)) / (2.0 * lmbda)

def transform_logit(x):
    x_pos = x - np.min(x) + 0.001
    x_unit = (x_pos - np.min(x_pos) + 0.001) / (np.max(x_pos) - np.min(x_pos) + 0.002)
    return np.log(x_unit / (1.0 - x_unit))

def transform_arcsine(x):
    x_pos = x - np.min(x) + 0.001
    x_unit = (x_pos - np.min(x_pos) + 0.001) / (np.max(x_pos) - np.min(x_pos) + 0.002)
    return np.arcsin(np.sqrt(x_unit))

def transform_fisher_z(x):
    x_pos = x - np.min(x) + 0.001
    x_corr = -0.99 + 1.98 * (x_pos - np.min(x_pos)) / (np.max(x_pos) - np.min(x_pos))
    return np.arctanh(x_corr)

def transform_bayesian_power(x, c=0.001, lmbda=0.5):
    x_pos = x - np.min(x) + c
    return (np.power(x_pos, lmbda) - 1.0) / lmbda

def transform_central_normalizing(x):
    ranks = stats.rankdata(x)
    p = (ranks - 0.375) / (len(x) + 0.25)
    return stats.norm.ppf(p)

def transform_modified_non_negative(x, lmbda=0.5):
    x_pos = x - np.min(x)
    return (np.power(x_pos + 1.0, lmbda) - np.power(x_pos + 1.0, -lmbda)) / (2.0 * lmbda)

transformations = {
    'Raw S&P 500 Returns': lambda x: x,
    'Box-Cox (Shifted)': transform_box_cox,
    'Bickel-Doksum': transform_bickel_doksum,
    'Manly': transform_manly,
    'Modulus (John-Draper)': transform_modulus,
    'Yeo-Johnson': transform_yeo_johnson,
    'Dual Power (Shifted)': transform_dual_power,
    'Logit (Scaled)': transform_logit,
    'Arcsine Square-Root (Scaled)': transform_arcsine,
    'Fisher z-Transform (Scaled)': transform_fisher_z,
    'Bayesian Power (Shifted)': transform_bayesian_power,
    'Central Normalizing (Quantile)': transform_central_normalizing,
    'Modified Non-Negative (Shifted)': transform_modified_non_negative,
    'Obulezi (Proposed)': fit_obulezi
}

# -------------------------------------------------------------------------
# 4. COMPUTE RESULTS TABLE & STANDARDIZE DATA FOR PLOTS
# -------------------------------------------------------------------------
results = []
std_dict = {}

all_keys = list(transformations.keys())

for name, func in transformations.items():
    try:
        y = func(real_data)

        # Standardize series (z-score) for standardized plotting
        std_dict[name] = (y - np.mean(y)) / np.std(y)

        abs_skew = np.abs(stats.skew(y))
        excess_kurt = stats.kurtosis(y)
        w_stat, p_val = stats.shapiro(y)

        results.append({
            'Transformation Family': name,
            'Absolute Skewness': abs_skew,
            'Excess Kurtosis': excess_kurt,
            'Shapiro-Wilk W': w_stat,
            'SW p-value': p_val
        })
    except Exception as e:
        print(f"Error computing {name}: {e}")

df_results = pd.DataFrame(results)

print("================ REAL EMPIRICAL DATA BENCHMARK (S&P 500: 2020–2023) ================")
print(df_results.to_string(index=False))
print("====================================================================================\n")

# -------------------------------------------------------------------------
# 5. PLOTTING SUITE (SAVES PDF/PNG & SHOWS ALL FIGURES)
# -------------------------------------------------------------------------
x_ref = np.linspace(-4, 4, 500)
norm_pdf = stats.norm.pdf(x_ref)
norm_cdf = stats.norm.cdf(x_ref)

def setup_grid():
    fig, axes = plt.subplots(4, 4, figsize=(14, 12), dpi=300)
    return fig, axes.flatten()

def finalize_and_save(fig, axes, name_prefix):
    for j in range(len(all_keys), 16):
        fig.delaxes(axes[j])
    plt.tight_layout()
    plt.savefig(f'{name_prefix}.pdf', dpi=300, bbox_inches='tight')
    plt.savefig(f'{name_prefix}.png', dpi=300, bbox_inches='tight')
    print(f"Plot saved successfully: {name_prefix}.pdf and {name_prefix}.png")
    plt.show()

# -------------------------------------------------------------------------
# PLOT 1: ALL 14 Q-Q PLOTS
# -------------------------------------------------------------------------
fig1, axes1 = setup_grid()
for i, name in enumerate(all_keys):
    ax = axes1[i]
    osm, osr = stats.probplot(std_dict[name], fit=False)
    color = 'darkred' if 'Obulezi' in name else ('navy' if 'Central' in name else 'steelblue')

    ax.scatter(osm, osr, color=color, alpha=0.5, s=8)
    ax.plot([-4, 4], [-4, 4], 'k--', linewidth=1.0)

    ax.set_xlim(-4.2, 4.2)
    ax.set_ylim(-4.2, 4.2)
    ax.set_title(name, fontweight='bold' if 'Obulezi' in name else 'normal')
    ax.grid(True, linestyle=':', alpha=0.5)
    if i % 4 == 0: ax.set_ylabel('Sample Quantiles')
    if i >= 10: ax.set_xlabel('Theoretical Quantiles')

finalize_and_save(fig1, axes1, 'all_transformations_qqplots')

# -------------------------------------------------------------------------
# PLOT 2: ALL 14 KERNEL DENSITY ESTIMATES (KDE)
# -------------------------------------------------------------------------
fig2, axes2 = setup_grid()
for i, name in enumerate(all_keys):
    ax = axes2[i]
    color = 'darkred' if 'Obulezi' in name else ('navy' if 'Central' in name else 'steelblue')

    sns.kdeplot(std_dict[name], ax=ax, color=color, linewidth=1.5)
    ax.plot(x_ref, norm_pdf, 'k--', linewidth=1.0)

    ax.set_xlim(-4.2, 4.2)
    ax.set_title(name, fontweight='bold' if 'Obulezi' in name else 'normal')
    ax.grid(True, linestyle=':', alpha=0.5)
    if i % 4 == 0: ax.set_ylabel('Density')
    if i >= 10: ax.set_xlabel('Standardized Value ($z$)')

finalize_and_save(fig2, axes2, 'all_transformations_kde')

# -------------------------------------------------------------------------
# PLOT 3: ALL 14 EMPIRICAL CUMULATIVE DISTRIBUTION FUNCTIONS (ECDF)
# -------------------------------------------------------------------------
fig3, axes3 = setup_grid()
for i, name in enumerate(all_keys):
    ax = axes3[i]
    color = 'darkred' if 'Obulezi' in name else ('navy' if 'Central' in name else 'steelblue')

    sorted_data = np.sort(std_dict[name])
    y_ecdf = np.arange(1, len(sorted_data) + 1) / len(sorted_data)

    ax.plot(sorted_data, y_ecdf, color=color, linewidth=1.5)
    ax.plot(x_ref, norm_cdf, 'k--', linewidth=1.0)

    ax.set_xlim(-4.2, 4.2)
    ax.set_ylim(-0.05, 1.05)
    ax.set_title(name, fontweight='bold' if 'Obulezi' in name else 'normal')
    ax.grid(True, linestyle=':', alpha=0.5)
    if i % 4 == 0: ax.set_ylabel('Cumulative Prob.')
    if i >= 10: ax.set_xlabel('Standardized Value ($z$)')

finalize_and_save(fig3, axes3, 'all_transformations_ecdf')

# -------------------------------------------------------------------------
# PLOT 4: COMPARATIVE OUTLIER BOXPLOT (HORIZONTAL)
# -------------------------------------------------------------------------
fig4, ax4 = plt.subplots(figsize=(12, 6), dpi=300)
df_box = pd.DataFrame(std_dict)

palette = ['darkred' if 'Obulezi' in col else ('navy' if 'Central' in col else 'lightblue') for col in df_box.columns]

sns.boxplot(data=df_box, ax=ax4, palette=palette, orient='h', fliersize=2.5)
ax4.axvline(x=0, color='black', linestyle='--', linewidth=1.0)
ax4.axvline(x=-1.96, color='gray', linestyle=':', linewidth=0.8)
ax4.axvline(x=1.96, color='gray', linestyle=':', linewidth=0.8)

ax4.set_xlim(-5, 5)
ax4.set_xlabel('Standardized Return Units ($z$-score)')
ax4.set_title('Outlier Dispersion and Heavy-Tail Compression Across Transformations', fontweight='bold')
ax4.grid(True, linestyle=':', alpha=0.6)

plt.tight_layout()
plt.savefig('all_transformations_boxplot.pdf', dpi=300, bbox_inches='tight')
plt.savefig('all_transformations_boxplot.png', dpi=300, bbox_inches='tight')
print("Plot saved successfully: all_transformations_boxplot.pdf and .png")
plt.show()