# -*- coding: utf-8 -*-
"""simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2jDMwEVrmaPWvoOXxWK1SmoS18csVbl
"""

import numpy as np
import scipy.stats as stats
from scipy.optimize import minimize_scalar
from scipy.special import lambertw
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

# -------------------------------------------------------------------------
# 1. CORE OBULEZI TRANSFORMATION & PROFILE LIKELIHOOD
# -------------------------------------------------------------------------

def obulezi_transform(x, lmbda):
    x = np.asarray(x, dtype=np.float64)
    sgn = np.sign(x)
    abs_x = np.abs(x)
    if np.isclose(lmbda, 0.0):
        return x
    elif lmbda > 0:
        return sgn * (1.0 / lmbda) * np.log(1.0 + lmbda * abs_x * np.exp(lmbda * abs_x))
    else:
        abs_lmbda = np.abs(lmbda)
        w_val = np.real(lambertw(abs_lmbda * abs_x))
        return sgn * (1.0 / abs_lmbda) * w_val

def obulezi_jacobian_log(x, lmbda):
    x = np.asarray(x, dtype=np.float64)
    abs_x = np.abs(x)
    if np.isclose(lmbda, 0.0):
        return np.zeros_like(x)
    elif lmbda > 0:
        num = 1.0 + lmbda * abs_x
        den = 1.0 + lmbda * abs_x * np.exp(lmbda * abs_x)
        return np.log(num) - np.log(den) + (lmbda * abs_x)
    else:
        abs_lmbda = np.abs(lmbda)
        w_val = np.real(lambertw(abs_lmbda * abs_x))
        mask = abs_x > 1e-12
        log_j = np.zeros_like(x)
        log_j[mask] = np.log(w_val[mask]) - np.log(abs_lmbda * abs_x[mask] * (1.0 + w_val[mask]))
        return log_j

def profile_log_lik_obulezi(lmbda, x):
    n = len(x)
    y = obulezi_transform(x, lmbda)
    y_var = np.var(y, ddof=0)
    if y_var <= 1e-12 or np.isnan(y_var) or np.isinf(y_var):
        return 1e10
    log_j = obulezi_jacobian_log(x, lmbda)
    return -(-0.5 * n * np.log(2 * np.pi) - 0.5 * n * np.log(y_var) - 0.5 * n + np.sum(log_j))

def fit_obulezi(x):
    res = minimize_scalar(profile_log_lik_obulezi, bounds=(-2.0, 2.0), args=(x,), method='bounded')
    return obulezi_transform(x, res.x)

# -------------------------------------------------------------------------
# 2. IMPLEMENTATION OF TABLE 1 TRANSFORMATIONS
# -------------------------------------------------------------------------

def transform_box_cox(x):
    x_pos = x - np.min(x) + 0.01
    y, _ = stats.boxcox(x_pos)
    return y

def transform_bickel_doksum(x, lmbda=0.5):
    sgn = np.sign(x)
    abs_x = np.abs(x)
    return (np.power(abs_x, lmbda) * sgn - 1.0) / lmbda

def transform_manly(x, lmbda=0.1):
    return (np.exp(lmbda * x) - 1.0) / lmbda if not np.isclose(lmbda, 0) else x

def transform_modulus(x, lmbda=0.5):
    sgn = np.sign(x)
    abs_x = np.abs(x)
    return sgn * ((np.power(abs_x + 1.0, lmbda) - 1.0) / lmbda)

def transform_yeo_johnson(x):
    y, _ = stats.yeojohnson(x)
    return y

def transform_dual_power(x, lmbda=0.5):
    x_pos = x - np.min(x) + 0.01
    return (np.power(x_pos, lmbda) - np.power(x_pos, -lmbda)) / (2.0 * lmbda)

def transform_logit(x):
    x_pos = x - np.min(x) + 0.01
    x_unit = (x_pos - np.min(x_pos) + 0.001) / (np.max(x_pos) - np.min(x_pos) + 0.002)
    return np.log(x_unit / (1.0 - x_unit))

def transform_arcsine(x):
    x_pos = x - np.min(x) + 0.01
    x_unit = (x_pos - np.min(x_pos) + 0.001) / (np.max(x_pos) - np.min(x_pos) + 0.002)
    return np.arcsin(np.sqrt(x_unit))

def transform_fisher_z(x):
    x_pos = x - np.min(x) + 0.01
    x_corr = -0.99 + 1.98 * (x_pos - np.min(x_pos)) / (np.max(x_pos) - np.min(x_pos))
    return np.arctanh(x_corr)

def transform_bayesian_power(x, c=0.01, lmbda=0.5):
    x_pos = x - np.min(x) + c
    return (np.power(x_pos, lmbda) - 1.0) / lmbda

def transform_central_normalizing(x):
    ranks = stats.rankdata(x)
    p = (ranks - 0.375) / (len(x) + 0.25)
    return stats.norm.ppf(p)

def transform_modified_non_negative(x, lmbda=0.5):
    x_pos = x - np.min(x)
    return (np.power(x_pos + 1.0, lmbda) - np.power(x_pos + 1.0, -lmbda)) / (2.0 * lmbda)

# Dictionary of all 12 methods from Table 1 + Baseline Raw Data
transformations = {
    'Raw Data': lambda x: x,
    'Box-Cox (Shifted)': transform_box_cox,
    'Bickel-Doksum': transform_bickel_doksum,
    'Manly': transform_manly,
    'Modulus (John-Draper)': transform_modulus,
    'Yeo-Johnson': transform_yeo_johnson,
    'Dual Power (Shifted)': transform_dual_power,
    'Logit (Scaled)': transform_logit,
    'Arcsine Square-Root (Scaled)': transform_arcsine,
    'Fisher z-Transform (Scaled)': transform_fisher_z,
    'Bayesian Power (Shifted)': transform_bayesian_power,
    'Central Normalizing (Quantile)': transform_central_normalizing,
    'Modified Non-Negative (Shifted)': transform_modified_non_negative,
    'Obulezi (Proposed)': fit_obulezi
}

# -------------------------------------------------------------------------
# 3. MONTE CARLO SIMULATION
# -------------------------------------------------------------------------

np.random.seed(42)
n_samples = 500
n_simulations = 100

sim_data = {name: {'skew': [], 'kurt': [], 'p_val': []} for name in transformations.keys()}

print("Running Monte Carlo Simulation across all 12 Table 1 transformations...")

for _ in range(n_simulations):
    # Heavy-tailed, skewed Student-t sample crossing zero into negative values
    x_raw = stats.t.rvs(df=3, loc=1.5, scale=2.0, size=n_samples) - 2.0

    for name, func in transformations.items():
        try:
            y = func(x_raw)
            sim_data[name]['skew'].append(np.abs(stats.skew(y)))
            sim_data[name]['kurt'].append(stats.kurtosis(y))
            _, p_val = stats.shapiro(y)
            sim_data[name]['p_val'].append(p_val)
        except Exception:
            sim_data[name]['skew'].append(np.nan)
            sim_data[name]['kurt'].append(np.nan)
            sim_data[name]['p_val'].append(0.0)

# -------------------------------------------------------------------------
# 4. AGGREGATE RESULTS TABLE
# -------------------------------------------------------------------------

table_rows = []
for name in transformations.keys():
    mean_skew = np.nanmean(sim_data[name]['skew'])
    mean_kurt = np.nanmean(sim_data[name]['kurt'])
    mean_p = np.nanmean(sim_data[name]['p_val'])
    rejection_rate = np.mean(np.array(sim_data[name]['p_val']) < 0.05)

    table_rows.append({
        'Transformation': name,
        'Mean |Skewness|': mean_skew,
        'Mean Excess Kurtosis': mean_kurt,
        'Mean SW p-value': mean_p,
        'SW Rejection Rate (p < 0.05)': rejection_rate
    })

df_all = pd.DataFrame(table_rows)
print("\n================ FULL BENCHMARK WITH TABLE 1 TRANSFORMATIONS ================")
print(df_all.to_string(index=False))